name: update

  # # at 4am at the first day of each month
  # on:
  #   schedule:
  #     - cron: "01 12 * * *"
  #     # - cron: "0 4 1 0 *"

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            lfs: 'true'
      - name: Install dependencies
        run: |
          pip install matplotx matplotlib requests rich
      - name: Create readme plots
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          python3 tools/create-readme-plots.py
      - name: Optimize files
        run: |
          npm install -g svgo
          svgo *.svg
          # and move them out of the way
          mkdir /tmp/plots/
          mv *.svg /tmp/plots/
      - name: Commit data
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Weirdly, we need to execute *some* git command here to refresh
          # git's internal status. Otherwise it'll incorrectly register a
          # number of changed files. This probably has to do with gitlfs.
          git status
          # https://stackoverflow.com/a/8123841/353337
          git diff-index --quiet HEAD || git commit -am "Automated update"
          git push
      - name: Commit plots
        run: |
          git fetch
          git checkout gh-pages
          mv /tmp/plots/*.svg .
          git add *.svg
          git diff-index --quiet HEAD || git commit -am "Automated update"
          git push
